spring:
  application:
    name: identityforge
  datasource:
    url: ${IAM_DB_URL}
    username: ${IAM_DB_USERNAME}
    password: ${IAM_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none

iam:
  http:
    allowed-origins: ${IAM_ALLOWED_ORIGINS}
  oauth:
    issuer: ${IAM_OAUTH_ISSUER}
  security:
    secret-encryption-key: ${IAM_SECRET_ENCRYPTION_KEY}
    signing-key-file: ${IAM_SIGNING_KEY_FILE}

app:
  admin-console:
    frontend-base-url: ${IAM_ADMIN_CONSOLE_URL}

server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax
        secure: ${IAM_COOKIE_SECURE:true}
